[project]
name = "meeting-service"
version = "0.1.0"
description = "Agendable Meeting Service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "common-lib",
  "databases>=0.9.0",
]

[tool.hatch.build.targets.wheel]
packages = []
include = ["app"]
