coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 0.1%
    patch:
      default:
        target: 85%
        threshold: 0%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
