repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.7
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        name: mypy-common-lib
        entry: mypy --config-file common-lib/mypy.ini
        language: system
        types: [python]
        files: ^common-lib/

    -   id: mypy
        name: mypy-meeting-service
        entry: mypy --config-file meeting-service/mypy.ini
        language: system
        types: [python]
        files: ^meeting-service/

    -   id: mypy
        name: mypy-user-service
        entry: mypy --config-file user-service/mypy.ini
        language: system
        types: [python]
        files: ^user-service/

# Disable pylint checks:
# C0103 (invalid-name)
# C0114 (missing-module-docstring)
# C0115 (missing-class-docstring)
# C0116 (missing-function-docstring)
# E0013 (bad-continuation)
# E0213 (no-self-argument)
# R0903 (too-few-public-methods)
# W0511 (fixme)
-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.3
    hooks:
    -   id: pylint
        args: ["--disable=C0103,C0114,C0115,C0116,E0013,E0213,R0903,W0511"]
        exclude: "alembic/.*"
