[project]
name = "Agendable"
version = "0.1.0"
description = "Agendable is an app for managing recurring meetings"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "async-asgi-testclient>=1.4.11",
    "asyncpg>=0.30.0",
    "common-lib>=0.1.3",
    "coverage>=7.7.0",
    "factory-boy>=3.3.3",
    "fastapi>=0.115.11",
    "greenlet>=3.1.1",
    "httpx>=0.28.1",
    "isort>=6.0.1",
    "loguru>=0.7.3",
    "mypy>=1.15.0",
    "pre-commit>=4.2.0",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
    "pylint>=3.3.6",
    "pytest-asyncio>=0.25.3",
    "python-dateutil>=2.9.0.post0",
    "redis>=5.2.1",
    "ruff>=0.11.1",
    "sqlalchemy>=2.0.39",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.isort]
profile = "black"
force_sort_within_sections = true
known_first_party = ["app"]

[tool.ruff]
exclude = [
    "**/__init__.py",
    "**/alembic/versions/**"
]
