[build-system]
requires      = ["hatchling>=1.10"]
build-backend = "hatchling.build"

[project]
name            = "common-lib"
version         = "0.1.0"
readme          = "README.md"
requires-python = ">=3.13"

[tool.hatch.build.targets.wheel]
packages = ["src/common_lib"]
